version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - speech-service
      - code-service
      - code-review-service
      - collaboration-service
      - weather-service
      - live-ai-coding-service
      - collaborative-docs-service
    environment:
      - SPEECH_SERVICE_URL=http://speech-service:8001
      - CODE_SERVICE_URL=http://code-service:8002
      - CODE_REVIEW_SERVICE_URL=http://code-review-service:8003
      - COLLABORATION_SERVICE_URL=http://collaboration-service:8004
      - WEATHER_SERVICE_URL=http://weather-service:8007
      - LIVE_AI_CODING_SERVICE_URL=http://live-ai-coding-service:8005
      - COLLABORATIVE_DOCS_SERVICE_URL=http://collaborative-docs-service:8006

  # Speech Service
  speech-service:
    build: ./services/speech-service
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  # Code Service
  code-service:
    build: ./services/code-service
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  # Code Review Service
  code-review-service:
    build: ./services/code-review-service
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  # Collaboration Service
  collaboration-service:
    build: ./services/collaboration-service
    ports:
      - "8004:8004"

  # Live AI Coding Service
  live-ai-coding-service:
    build: ./services/live-ai-coding-service
    ports:
      - "8005:8005"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  # Collaborative Documents Service
  collaborative-docs-service:
    build: ./services/collaborative-docs-service
    ports:
      - "8006:8006"

  # Weather Service
  weather-service:
    build: ./services/weather-service
    ports:
      - "8007:8007"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000 