apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: codevoice
  labels:
    app: api-gateway
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: backend
    spec:
      containers:
      - name: api-gateway
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/codevoice/api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: SPEECH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: SPEECH_SERVICE_URL
        - name: CODE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: CODE_SERVICE_URL
        - name: CODE_REVIEW_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: CODE_REVIEW_SERVICE_URL
        - name: COLLABORATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: COLLABORATION_SERVICE_URL
        - name: WEATHER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: WEATHER_SERVICE_URL
        - name: LIVE_AI_CODING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: LIVE_AI_CODING_SERVICE_URL
        - name: COLLABORATIVE_DOCS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: COLLABORATIVE_DOCS_SERVICE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: REDIS_URL
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: codevoice-config
              key: POSTGRES_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: codevoice-secrets
              key: OPENAI_API_KEY
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: codevoice-secrets
              key: OPENWEATHER_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: codevoice
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 