apiVersion: v1
kind: ConfigMap
metadata:
  name: codevoice-config
  namespace: codevoice
data:
  # API Gateway Configuration
  API_GATEWAY_PORT: "8000"
  
  # Service URLs (internal cluster DNS)
  SPEECH_SERVICE_URL: "http://speech-service:8001"
  CODE_SERVICE_URL: "http://code-service:8002"
  CODE_REVIEW_SERVICE_URL: "http://code-review-service:8003"
  COLLABORATION_SERVICE_URL: "http://collaboration-service:8004"
  WEATHER_SERVICE_URL: "http://weather-service:8007"
  LIVE_AI_CODING_SERVICE_URL: "http://live-ai-coding-service:8005"
  COLLABORATIVE_DOCS_SERVICE_URL: "http://collaborative-docs-service:8006"
  
  # Frontend Configuration
  NEXT_PUBLIC_API_URL: "http://api-gateway-service:8000"
  
  # Redis Configuration
  REDIS_URL: "redis://codevoice-redis:6379"
  
  # PostgreSQL Configuration
  POSTGRES_URL: "postgresql://codevoice:password@codevoice-postgres:5432/codevoice"
  
  # Rate Limiting
  RATE_LIMIT: "100"
  
  # CORS Origins
  CORS_ORIGINS: "https://codevoice.yourdomain.com,http://localhost:3000" 