apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-ai-coding-service
  namespace: codevoice
  labels:
    app: live-ai-coding-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: live-ai-coding-service
  template:
    metadata:
      labels:
        app: live-ai-coding-service
        tier: backend
    spec:
      containers:
      - name: live-ai-coding-service
        image: codevoice/live-ai-coding-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: codevoice-secrets
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: live-ai-coding-service
  namespace: codevoice
  labels:
    app: live-ai-coding-service
spec:
  selector:
    app: live-ai-coding-service
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
  type: ClusterIP 