apiVersion: v1
kind: Secret
metadata:
  name: codevoice-secrets
  namespace: codevoice
type: Opaque
data:
  # Base64 encoded secrets (you'll need to encode these)
  # echo -n "your-openai-api-key" | base64
  OPENAI_API_KEY: "eW91ci1vcGVuYWktYXBpLWtleS1oZXJl"  # Replace with actual base64 encoded key
  OPENWEATHER_API_KEY: "eW91ci13ZWF0aGVyLWFwaS1rZXktaGVyZQ=="  # Replace with actual base64 encoded key
  
  # Database credentials
  POSTGRES_USER: "Y29kZXZvaWNl"  # codevoice
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="  # password
  POSTGRES_DB: "Y29kZXZvaWNl"  # codevoice
  
  # Redis password (if needed)
  REDIS_PASSWORD: "cmVkaXNwYXNzd29yZA=="  # redispassword 