apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-service
  namespace: codevoice
  labels:
    app: speech-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speech-service
  template:
    metadata:
      labels:
        app: speech-service
        tier: backend
    spec:
      containers:
      - name: speech-service
        image: codevoice/speech-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: codevoice-secrets
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: speech-service
  namespace: codevoice
  labels:
    app: speech-service
spec:
  selector:
    app: speech-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP 